### ISSUE TITLE
could i use this board to connect kiwisdr?

### ISSUE THREAD

**Issue by taskx6004** [electrosense/hardware#1]
Hi, I need a simple and elegant design to connect kiwisdr, I saw recent update v2 board has deleted only one RF route connected to the up converter mixer, is it capable to mix 60MHz-6Ghz in firmware? Some modification require for RF parts maybe required but I am not sure. I can help with your new board assembly (in Shenzhen).

**Comment by ingframin** [comment]
Hello, the circuit is exactly the same in version 2. I simply removed a connector and few components that were not used anymore in later iterations. The redesign is actually a cost reduction rather then a functional redesign. You can for sure use this with the kiwi sdr. As for assembly I am not in a position to change our supplier.

**Comment by taskx6004** [comment]
Thanks for the reply, I will try to layout a version without up converter, and look into the firmware.

**Comment by ingframin** [comment]
Start from V1 though... The V2 is still work in progress and it doesn't really work yet. Also, if you build V2, mark C30 as DNP or you need to change the firmware to disable MCO and use the TCXO as reference for the PLL.

**Comment by taskx6004** [comment]
![wbmix_00](https://user-images.githubusercontent.com/7752512/115064073-13cdf780-9f1f-11eb-9c09-987f032a5a61.png)
I am porting the design in KiCAD (5.99/6), due to current shortage of ICs, some parts may need to be replaced, I will check my sch and send BOM for availability check. I hope it won't be too hard to put it on a 5x5 cm with 0.4/0.2 via 4 layer board.

If it's appropriate I hope continue using this issue for further questions and hope you can help me figure it out.

**Comment by taskx6004** [comment]
![Screenshot from 2021-04-19 21-29-04](https://user-images.githubusercontent.com/7752512/115250590-4d3f7680-a15c-11eb-8096-a6551790235c.png)

Hi, I spend some time to re-layout the v1 design by using KiCAD. And here are some concerns about my layout: 

- the TCXO output to MCU and the LO Line to up converter part will inevitably cross, i have to use a via jump to feed the XO clock to MCU.
- currently the MCU is more than 10USB, would it be feasible to do it on a STM32g431 or newer more available chips?
- the trace is 50 ohm controlled. but the clock branching and tracing is cornered. I don't know how this board will perform.
Any advice for me? Thank you in advance.

**Comment by BertoldVdb** [comment]
You do not need to connect the TCXO to the MCU. If you use one of the newer MCU you can even use the internal oscillator as the accurate clock is only used for USB.

I think it should be quite easy to use another MCU. I find STM32 in general difficult to find at the moment.

The upconverter does not perform well, it was only added to meet a specification requirement.
