### ISSUE TITLE
Can it be use on a LimeSDR (which is limited to 3.8GHz)?

### ISSUE THREAD

**Issue by OhSoGood** [electrosense/hardware#2]
Hi,
Congratulation for the project, and it's so nice to share it with everybody.

I offered myself a nice LimeSDR a few months ago (it goes up to 3.8GHz), and I was wondering if I could use your board for both RX and TX up to 6GHz? If so, with V1 or V2 of the board?

Are there any drawback you know to use such a converter? RF bandwidth limitation, I/Q balance, interference/harmonics, whatsoever ?

Thanks again

**Comment by BertoldVdb** [comment]
Hi,

Yes, it will work with a LimeSDR or any other receiver that can use the
1.575GHz IF. The bandwidth with the filter mentioned in the BOM is quite
low, as it was made for the rtl-sdr. You can replace it with another GPS
SAW with a wider passband.

Sincerely,
Bertold

Op ma 19 jul. 2021 18:27 schreef OhSoGood ***@***.***>:
